### PR TITLE
Farsi Weekdays!

### PR DESCRIPTION
**Pull request by aryanbadiee**
i think it's better that you set farsi weekdays instead of english weekdays
if you agree with me, merge it
thanks for this library.

### CODE REVIEW

**Comment by slashmili** [comment]
Not sure about it. when the local is not 'fa_IR' we use English letters.

what do you think @farzadghanei / @hramezani

**Comment by aryanbadiee** [comment]
but you used Persian months in default local like Farvardin, Dey, Tir, ...
Why not use Persian weekdays?!
but i respect to your opinion and other

**Comment by slashmili** [comment]
@aryanbadiee because when it's Farvardin, it's between March and April. But when It's Sunday it's Sunday all around the globe!

To be honest I don't have much strong opinion on this but the main problem is if we make this change, since it's a breaking change, we should bump the version from `3.6.2` to `4.0.0` and the library is not ready to make this MAJOR version change only because of weekdays name 😞

**Comment by aryanbadiee** [comment]
Alright, it's logical👍

**Comment by farzadghanei** [comment]
IMO there is nothing wrong with current naming of months. The names of the months are correct without translation (Farvardin, etc.) because there is no direct correlation between Jalali months and Gregorian. But week days are the same, for all calendars. Unfortunately I would strongly vote not to merge the PR. Thanks for contributing though.

**Comment by aryanbadiee** [comment]
@farzadghanei ok.
thanks too

**Comment by slashmili** [comment]
Thanks for your understating. I'll consider this change when we have a major release.

**Pull request closed without merging**
