### PR TITLE
Add python3.9 support.

### PR DESCRIPTION
**Pull request by hramezani**
* Add python3.9 support.
* Add supported Python versions badge to README

### CODE REVIEW

**Comment by hramezani** [comment]
It seems we have to wait till `travis-ci` and `appveyor` add support for `Python3.9`

**Comment by farzadghanei** [comment]
Until the CI providers support Python 3.9, merging this PR doesn't seem to be a good idea. @hramezani did you run the tests locally with 3.9?

**Comment by hramezani** [comment]
@farzadghanei 
> did you run the tests locally with 3.9?

Yes, They passed successfully.

**Comment by hramezani** [comment]
It is ready to merge now!

**Review by farzadghanei — APPROVED** [review]
:+1: Thanks

**Comment by slashmili** [comment]
Thanks @hramezani 🎉

**Pull request merged**
