### PR TITLE
Add season

### PR DESCRIPTION
**Pull request by saeed-raeisi**
Season show added
Test updated
Season display format %Q

### CODE REVIEW

**Comment by saeed-raeisi** [comment]
The existing problems were solved
The tests were updated

**Comment by slashmili** [comment]
Thanks for your contribution @saeed-raeisi 🙇 

Does python datetime support `%Q`  directive? I couldn't find it in this [doc](https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior)

**Comment by saeed-raeisi** [comment]
Actually
This format was available in the babel library

And I needed it in my program

**Comment by saeed-raeisi** [comment]
If there are no places to add this format, we should start developing the local fa_IR version of this library
https://github.com/python-babel/babel

**Comment by slashmili** [comment]
@saeed-raeisi this project goal is to have feature parity with `datetime`  module.

Therefor I'm hesitant to accept this PR. However I understand that you need it to make your project works 🤔 

What do you think @farzadghanei / @hramezani?

**Comment by hramezani** [comment]
Agree with you @slashmili

**Comment by saeed-raeisi** [comment]
I understand so I need to localize babel 🙂  🇮🇷
[babel](https://github.com/python-babel/babel)
Thank you for your attention 🌹

**Comment by slashmili** [comment]
@saeed-raeisi thanks for you understanding 🙇

**Pull request closed without merging**
