### PR TITLE
add unicode format in `strftime` method.

### PR DESCRIPTION
**Pull request by hramezani**

### CODE REVIEW

**Comment by slashmili** [comment]
@hramezani what is the use case for this one? does it fix this isssue https://github.com/slashmili/django-jalali/issues/38 ?

**Comment by hramezani** [comment]
> what is the usecase for this one?

by this change we can use unicode format in `strftime` like:
`jdatetime.datetime.now().strftime('ﺱﺎﻟ = %y، ﻡﺎﻫ =  %m، ﺭﻭﺯ = %d')`

> does it fix this issue ...?
yes, but i have to deliver new version of jformat filter in a pull request, i test it in my mashine and it seems ok.

**Comment by slashmili** [comment]
Thanks!

**Comment by slashmili** [comment]
Update the package in pypi to 1.8.2

**Pull request merged**
