### PR TITLE
Add Python 3.10 to github action test workflow.

### PR DESCRIPTION
**Pull request by hramezani**

### CODE REVIEW

**Review by slashmili — APPROVED** [review]
LGTM 👍 

Thanks!

**Comment by hramezani** [comment]
@slashmili I don't have permission to merge it. Please merge this PR whenever you have time.

**Comment by hramezani** [comment]
@slashmili Could you please merge this PR or give me merge access?

**Comment by slashmili** [comment]
@hramezani sorry about that. I've added you to this project

**Pull request merged**
