### PR TITLE
fix(date, datetime): return NotImplemented for unknown type operations

### LINKED ISSUE #84: __add__ and __sub__ should return NotImplemented
You should return NotImplemented in arithmetic operations. Suppose I am using a library and the object of a class in this library knows how to do arithmetic operations and this object is the right object of arithmetic operations. (suppose this expression: a + b. "a" is an instance of `jdatetime` and "b" is the object of my library). When you raise an exception, the interpreter cannot reach to __radd__ method of the object of the class in my library("b" in my example).

Related links:
[NotImplemented](https://docs.python.org/3/reference/datamodel.html#the-standard-type-hierarchy)
[Implementing the arithmetic operations](https://docs.python.org/3/library/numbers.html#implementing-the-arithmetic-operations)

* jdatetime version:3.6.0
* Python version:3.9
* OS: ubuntu

### PR DESCRIPTION
**Pull request by 5j9**
This is how the built-in `date` and `datetime` work.

closes #84

### CODE REVIEW

**Comment by slashmili** [comment]
True, requires a major version. I think(might be wrong) this error format was how the datetime in python2 used to work

**Comment by 5j9** [comment]
Just to be clear, although this can be considered a breaking change, but the behaviour for almost all usual cases has not changed at all. `datetime.date.today() + 1` still raises `TypeError: unsupported operand type(s) for +: 'datetime.date' and 'int'`.

`NotImplemented `  is just a special value that tells the interpreter to retry the operation on the other operand and if that fails too, then the interpreter will raise `TypeError` as before.

So, the breaking behaviour only occurs if the right operand is implemented in a way that can handle `jdatetime.date` class but they rely on `date` to raise a TypeError and prevent the operation. This sound like an extremely unlikely scenario to me.

**Review by hramezani — APPROVED** [review]

**Comment by hramezani** [comment]
@slashmili I think we can merge it. what do you think?

**Comment by slashmili** [comment]
@hramezani Yes!

I'd say we only bump the minor version and hope for the best, what do you think?

otherwise we have to keep this change until next major release which we don't have any plan to do so

**Comment by hramezani** [comment]
> @hramezani Yes!
> 
> I'd say we only bump the minor version and hope for the best, what do you think?
> 
> otherwise we have to keep this change until next major release which we don't have any plan to do so

Sounds good to me 👍

**Comment by slashmili** [comment]
Thanks @5j9 🎉

**Pull request merged**
