### PR TITLE
Locale improvements on strftime() and date class.

### PR DESCRIPTION
**Pull request by Alireza2n**
```
Added locale param to strftime(). 
Added locale param to date object.
Restructured _is_fa_locale() to look for locale in object-level. 
```
These improvements allows strftime() and other methods printing similar outputs to be more flexible regarding locale settings and eliminates the need to change env or python level locale settings to use FA_LOCALEs.

### CODE REVIEW

**Comment by mehdisadeghi** [comment]
@Alireza2n which problem are you solving here?

**Comment by Alireza2n** [comment]
@mehdisadeghi
While working on multi lingual projects (especially in django), we find it hard to switch between locales in minimalist and isolated manner, for example changing locale in environment may cause unexpected issues with other packages, changing using python's setlocale() to constantly change app-level seems unclean and repetitive. 
So we came up with the idea that it would be nice to be able to change that specific strftime() or date instance's locale.

**Comment by mehdisadeghi** [comment]
@Alireza2n Django has built-in support for per-request locale. See Django i18n docs. What you are doing here, is basically shifting the state of your application to this package. You can of course subclass/patch the types defined here and use them as you wish, but I consider this outside the scope of this package.

**Comment by slashmili** [comment]
@Alireza2n, your concern is valid. give us sometime to review the Django i18n.

cc @farzadghanei

**Comment by slashmili** [comment]
@Alireza2n may I know how do you use it in your Django? I mean in templates or other places that you use it.

**Comment by farzadghanei** [comment]
@Alireza2n thanks for your interest in this project.
First I'd like to point out that this library is a generic date library and is not tied to a specific framework, so decisions regarding how the library evolves should be agnostic to such contexts.

@slashmili I also find the described concern understandable. `date` object's configuration is based on the locale (either set by current process, or system default), but there maybe contexts where the caller needs to configure the locale directly without affecting the environment.

However IMO current implementation, while trying to solve the said problem, is fragile. Passing `locale` to `strftime` is changing the state of the object, which is prone to errors. This maybe described as an example of violation of [CQS](https://en.wikipedia.org/wiki/Command%E2%80%93query_separation).

```python
date = jdatetime.date(1394, 12, 4)
# date is using default locale
print date.strftime("%a, %d %b %Y", locale='fa_IR')
# from now on date is using fa_IR locale which is not a welcome side effect
```

I think a safer approach here is to configure the instance's `locale` on `__init__` (where we're currently doing so by calling `_is_fa_locale()` and validate the argument (at least the format, more on this later). Then providing a [property](https://docs.python.org/2/library/functions.html#property) is more favorable than having a public attribute.
I understand there might be a concern with this approach, which is when the application did not initialize the `date` instance, say another library creates `date` objects (for example a Django wrapper, etc.) yet application still needs to format the `date` in a different locale. Although passing the `locale` to `strtime` may seem to solve the issue, for such cases I suggest the caller would clone the `date` object, and change the locale of the new instance and then call `strftime`, so still we won't need to pass the `locale` to `strftime`. 

I'd also suggest this `locale` parameter to follow Python standard library [locale format](https://docs.python.org/2/library/locale.html#locale.getlocale), which is a tuple of `(language code, encoding)` to provide an API more compatible with stdlib.

On a side note, having a mutable `locale` attribute on the `date` object, requires `strftime` to check for `locale` on each call, which means implementation of `_is_fa_locale()` would better avoid unnecessary operations, to keep this performance penalty minimum. So I'd defer getting process/system locales to only when they are actually required, wheres current implementation *always* calls both `_locale.getlocale()` and `_locale.getdefaultlocale()`, even when the object has an explicit `locale` set.

If you're having a case where the suggested approach won't be sufficient, could you please share the context?

**Comment by Alireza2n** [comment]
@slashmili 
Sorry for the late reply, I've been too tired to think about code for a while . :)
I this case, I have a calendar, system locale is set to en-UTF8, it simply renders a list of days.
Days are printed in their english names, but we need the Farsi names, without having to change the whole system or proccess locale.

Template:
`
{{ item.date|jajali_date_format:"%y-%m-%d" }}
`

Related field in model:
`
date = jmodels.jDateField(verbose_name=_('date'), unique=True)
`

and the template tag:
`
def jajali_date_format(value, fmt=None):
    if not fmt:
        fmt = settings.DEFAULT_TIMEFORMAT
    try:
        return value.strftime(fmt)
    except AttributeError as e:
        print("Object is not of type date")
        return value
`

**Comment by Alireza2n** [comment]
@farzadghanei 
cc @slashmili 

Hi!
Thanks for the complete explanation of aspects for proposed changes.

Reading your comment, I agree on the solution being fragile and may cause unwanted side-effects, maybe it would have been better if the locale only affected that specific call. But again we're changing the original signature of method, comparing to original strftime().

> I think a safer approach here is to configure the instance's locale by accepting the locale in __init__ 
Actually this was our first idea when solving the issue, but as you've already mentioned, the date instance has been initialized way before the method call, hence changing the attribute would not have any effects.
(unless we dig dipper into the code and other methods).

Given the discussion, I think there are two options:
1. Modify changes in strftime() to make sure it only affects that specific call only (fixing the fragility). 
2. Add an `locale` parameter to `__init__` and in application while processing the date objects, make copy of them and change their locale on-the-fly. (In my case, this may mean I need to modify other packages such as django-jalali)

I'm thinking option 1.

What is your opinion?

**Comment by slashmili** [comment]
@Alireza2n just to be clear, you do have some configurations like this, is correct?
```py
LANGUAGE_CODE = 'fa-ir'

LANGUAGES = (
  ('es', 'Spanish'),
  ('en', 'English'),
)

```

**Comment by Alireza2n** [comment]
@slashmili 

That is correct, here is an my settings.py:

```python
....
# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True
....
```

**Comment by farzadghanei** [comment]
@Alireza2n 

> But again we're changing the original signature of method, comparing to original strftime(). I dont know if changing signature is a bad practice or not.

It's not necessarily bad practice, however (quoting the project description):

> jdatetime is Jalali implementation of Python's datetime module

and
 
> This module exactly follows Python Standard datetime module's methods 

So it's preferred to avoid any deviation from the standard library API as much as possible. IMO adding extra class/module level functions is fine, even extending the `__init__` seems less than a deviation than changing signature of random methods.
In this case, since the desired behavior can be achieved outside of the library, it would not justify to change the signature of `strftime`.

An example of such solution is by adding the `locale` property to the `jdatetime` class, and providing an extra method on `jdatetime` class, say `aslocale()` (following [astimezone](https://docs.python.org/release/2.7.1/library/datetime.html#datetime.datetime.astimezone)) to return a `jdatetime` instance with the same timestamp, but in a different `locale`. Then the user of the library (say a Django template filter, etc.) decides the locale (say from request, DB, etc.) and calls `aslocale`, before `strftime`:

```python
value.aslocale(locale).strftime(fmt)
```

This way we even won't need to change the signature of `__init__`. 

On the other hand this seems a valid and useful feature to have for `jdatetime` to select the default `locale` in a way other than only the environment (system or process level locale), so we can work on that.

**Comment by slashmili** [comment]
@farzadghanei I like the `aslocale` idea 👍

**Comment by farzadghanei** [comment]
Great!
By the way to be able to set the default locale without changing the environment (process or system level locale settings) we have https://github.com/slashmili/python-jalali/pull/35, could be helpful.

**Pull request closed without merging**
