### PR TITLE
Add timetuple and timestamp methods

### PR DESCRIPTION
**Pull request by sassanh**

### CODE REVIEW

**Comment by farzadghanei** [comment]
@sassanh Thanks for the patch.
However [datetime.timetuple](https://github.com/slashmili/python-jalali/blob/ad5f030a9fe74feef07c624d1f06821df8c7a928/jdatetime/__init__.py#L1189) is already defined.

Implementation is only proxying to the wrapped Gregorian instance, so if we need this method on [date](https://docs.python.org/2/library/datetime.html#datetime.date.timetuple) objects as well, we can move `timetuple` definition to `date` class, and it'll be [inherited](https://github.com/slashmili/python-jalali/blob/ad5f030a9fe74feef07c624d1f06821df8c7a928/jdatetime/__init__.py#L639) properly by `datetime`.
It's unfortunate that we're missing tests for this method, that could be a great contribution :wink: 

About the new `timestamp` method, it's a new method for `datetime` added in [Python 3.3](https://docs.python.org/3/library/datetime.html#datetime.datetime.timestamp). If we want to add this method, the `jdatetime` library would be a Python 3.3+ only package, and I think we should discuss more with @slashmili before we decide to drop Python 2 compatibility.
For the time being, since the implementation is proxying to the wrapped Gregorian instance, I think it's easier to keep the call out of the library, and the application calls it directly:

```python
# myjd is a jdatetime instance
myjd.togregorian().timestamp()
```

By the way the [failing tests](https://travis-ci.org/slashmili/python-jalali/jobs/484169398) report a PEP8 formatting issue:
```
jdatetime/__init__.py:825:1: W293 blank line contains whitespace
```

**Comment by sassanh** [comment]
I wonder how I missed the existing `timetuple` method, I removed the duplicate and fixed the lint issue.
I also added tests for `timetuple` and `timestamp` methods, and now `timestamp` checks if underlying datetime module has `timestamp` method and if not, it'll raise a `NotImplementedError`.

**Comment by slashmili** [comment]
Thanks to both of you! 🎉

**Comment by slashmili** [comment]
Pushed to [pypi](https://pypi.org/project/jdatetime/3.2.0/)  as `3.2.0`

**Pull request merged**
